#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-google-api-java-client
Version  : 1.23.0
Release  : 1
URL      : https://github.com/googleapis/google-api-java-client/archive/1.23.0.tar.gz
Source0  : https://github.com/googleapis/google-api-java-client/archive/1.23.0.tar.gz
Source1  : https://repo1.maven.org/maven2/com/google/api-client/google-api-client-parent/1.23.0/google-api-client-parent-1.23.0.pom
Source2  : https://repo1.maven.org/maven2/com/google/api-client/google-api-client/1.23.0/google-api-client-1.23.0.jar
Source3  : https://repo1.maven.org/maven2/com/google/api-client/google-api-client/1.23.0/google-api-client-1.23.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-google-api-java-client-data = %{version}-%{release}

%description
# Google APIs Client Library for Java
- [Library maintenance](#maintenance)
- [Overview](#Overview)
- [Highlighted Features](#Highlighted_Features)
- [Dependencies](#Dependencies)
- [Important Warnings](#Beta)
- [@Beta](#Beta)
- [Deprecations](#Deprecations)
- [Documentation](#Documentation)
- [Links](#Links)

%package data
Summary: data components for the mvn-google-api-java-client package.
Group: Data

%description data
data components for the mvn-google-api-java-client package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/google/api-client/google-api-client-parent/1.23.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/google/api-client/google-api-client-parent/1.23.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/google/api-client/google-api-client/1.23.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/google/api-client/google-api-client/1.23.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/google/api-client/google-api-client/1.23.0
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/com/google/api-client/google-api-client/1.23.0


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/google/api-client/google-api-client-parent/1.23.0/google-api-client-parent-1.23.0.pom
/usr/share/java/.m2/repository/com/google/api-client/google-api-client/1.23.0/google-api-client-1.23.0.jar
/usr/share/java/.m2/repository/com/google/api-client/google-api-client/1.23.0/google-api-client-1.23.0.pom
